const DataVuelos = [
  {
    id: '1',
    departureAirport: 'BEG',
    departureCountry: 'Serbia',
    arrivalAirport: 'AMS',
    arrivalCountry: 'Netherlands',
    date: 'September 3, 2024',
    passengerCant: '2',
  },
  {
    id: '1',
    departureAirport: 'BEG',
    departureCountry: 'Serbia',
    arrivalAirport: 'AMS',
    arrivalCountry: 'Netherlands',
    date: 'September 3, 2024',
    passengerCant: '2',
  },
  {
    id: '1',
    departureAirport: 'BEG',
    departureCountry: 'Serbia',
    arrivalAirport: 'AMS',
    arrivalCountry: 'Netherlands',
    date: 'September 3, 2024',
    passengerCant: '2',
  },
  {
    id: '1',
    departureAirport: 'BEG',
    departureCountry: 'Serbia',
    arrivalAirport: 'AMS',
    arrivalCountry: 'Netherlands',
    date: 'September 3, 2024',
    passengerCant: '2',
  },
  {
    id: '1',
    departureAirport: 'BEG',
    departureCountry: 'Serbia',
    arrivalAirport: 'AMS',
    arrivalCountry: 'Netherlands',
    date: 'September 3, 2024',
    passengerCant: '2',
  },
  {
    id: '1',
    departureAirport: 'BEG',
    departureCountry: 'Serbia',
    arrivalAirport: 'AMS',
    arrivalCountry: 'Netherlands',
    date: 'September 3, 2024',
    passengerCant: '2',
  },
  {
    id: '1',
    departureAirport: 'BEG',
    departureCountry: 'Serbia',
    arrivalAirport: 'AMS',
    arrivalCountry: 'Netherlands',
    date: 'September 3, 2024',
    passengerCant: '2',
  },
];
